 <!-- FileName: /module/Blog/view/blog/list/detail.phtml -->
 <h2>Tankstelle Details</h2>

<div class="row">
    <div class="col-lg-3">
        <div class="panel panel-default">
            <div class="panel-heading">
                <div class="panel-title">Adresse
                    <a href="<?php echo $this->url( 'fuelstation/edit', array('id' => $station->getId()) ); ?>"><img src="<?php echo $this->basePath('images/edit.png') ?>" alt="edit" align="right"/></a>
               </div>
            </div>
            <div class="panel-body">
                <dl>
                     <dd><?php echo $this->escapeHtml($this->station->getStationId());?></dd>
                     <dd><?php echo $this->escapeHtml($this->station->getStreet());?></dd>
                     <dd><?php echo $this->escapeHtml($this->station->getPostalCode());?>&nbsp;<?php echo $this->escapeHtml($this->station->getCity());?></dd>
                </dl>
            </div>
        </div>
    </div>
    <div class="col-lg-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <div class="panel-title">Geodaten</div>
            </div>
            <div class="panel-body">
                <dl>
                     <dd>L&auml;nge: <?php echo $this->escapeHtml($this->station->getGeoCoordinateLatitude());?></dd>
                    <dd>Breite: <?php echo $this->escapeHtml($this->station->getGeoCoordinateLongitude());?></dd>
                    <dd><?php echo $this->map_html; ?></dd>
                </dl>
            </div>
        </div>
    </div>
</div>
