<!-- Filename: /module/Blog/view/blog/list/index.phtml -->
 <h2>Tankstellenverzeichnis</h2>

 <?php foreach ($this->stations as $station): ?>
 <article>
         <h4><a href="<?php echo $this->url( 'fuelstation/detail', array('id' => $station->getId()) ); ?>"><?= $station->getStationId() ?></a></h4>
    <p>
         <?= $station->getStreet() ?>,&nbsp;<?= $station->getPostalCode() ?>&nbsp;<?= $station->getCity() ?>
         <a href="<?php echo $this->url( 'fuelstation/edit', array('id' => $station->getId()) ); ?>">edit</a>
   </p>
 </article>
  <?php endforeach ?>
  <?php echo $this->map_html; ?>
  <p>
  <a href="<?php echo $this->url( 'fuelstation/add'); ?>">Tankstelle anlegen.</a>
  </p>